version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/is-5600-week-07/node-src
    volumes:
      - ..:/workspaces:cached
    environment:
      - PORT=3080
    networks:
      - app-network
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=products-db
    networks:
      - app-network

  app:
    image: mcr.microsoft.com/devcontainers/universal:2
    working_dir: /src
    volumes:
      - ..:/workspaces:cached
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
